### ISSUE TITLE
hallo

### ISSUE THREAD

**Issue by pet3r-pan** [cag/d-corp#1]
🅷🅴🅻🅻🅾 🆃🅷🅴🆁🅴 🅸 🅻🅸🅺🅴 🆈🅾🆄🆁 🅼🅴🅼🅴🆂

🅳🅾 🆈🅾🆄 🅷🅰🆅🅴 🆃🅴🅻🅴🅶🆁🅰🅼 🅱🆈 🅰🅽🆈 🅲🅷🅰🅽🅲🅴?

🅼🅸🅽🅴 🅸🆂 @ 🅿🅴🆃3🆁🅿🅰🅽 

🅻🅾🆅🅴 🆃🅾 🅶🅴🆃 🅸🅽 🆃🅾🆄🅲🅷

**Comment by cag** [comment]
＠🅰🅻🅰🅽🅻🆄⑩②③
